repos:
  - repo: local
    hooks:
      - id: commitizen
        name: commitizen
        entry: cz check
        args: [--commit-msg-file]
        require_serial: true
        language: system
        stages: [commit-msg]
      - id: absolufy-imports
        name: absolufy-imports
        entry: absolufy-imports
        require_serial: true
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        require_serial: true
        language: system
        types: [python]